<Project Sdk="Microsoft.NET.Sdk">

  <!-- Directory.Build.props provides TargetFramework, Nullable, ImplicitUsings -->
  <PropertyGroup>
    <AssemblyName>Tessra.Platform.Domain</AssemblyName>
    <RootNamespace>Tessra.Platform.Domain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant.Abstractions" Version="10.1.2" />
  </ItemGroup>

</Project>
